services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: eevex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - eevex-db:/var/lib/postgresql/data

volumes:
  eevex-db:
